name: Octokit Authentication

on: push

jobs:
  job-1:
    name: Secret Job
    runs-on: ubuntu-latest
    steps:
    - name: My action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo "Token passed to environment variable"
        
        
