name: Secrets

on: push

jobs:
  job-1:
    name: Secret Job
    runs-on: ubuntu-latest
    steps:
      - name: Secret Action
        env:
          secret: ${{ secrets.PAT }}
          run: |
            echo "Secret passed to environment variable"
